apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  # name: ros2-cs9
  generateName: ros2-cs9-container-job-
  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[master, main]"
spec:
  pipelineRef:
    name: container-build
  taskRunSpecs:
    - pipelineTaskName: build
      serviceAccountName: pipeline-buildah
  params:
    - name: SCM_URL
      value: "https://gitlab.com/fedora/sigs/robotics/images/ros2-cs9.git"
    - name: SCM_REFS
      value: "main"
    - name: RUNNER_IMAGE
      value: "quay.io/lrossett/tekton-runner:latest"
    - name: IMAGE_NAME
      value: "quay.io/lrossett/ros2-cs9:latest"
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 20Gi 
